default_profile = "Postgres"

[profiles.Postgres]
adapter = "postgres"
theme = "catppuccin-mocha"
limit = 100000
keymap_name = ["vscode"]
host = "localhost"
port = "5555"
dbname = "notifications"
user = "postgres"
password = "postgres"
