### 

# CreateUser

POST localhost:3000/auth/create HTTP/1.1
Content-Type: application/json

{
  "email": "ggbertomeu@gmail.com",
  "password": "kinga1234"
}


### 

# GetUser

GET localhost:3000/auth/1e04bf85-16d2-4542-a80e-4629e44c6411 HTTP/1.1
Content-Type: application/json
