services:
  broker:
    image: nats
    ports:
      - '8222:8222'
    networks:
      - brtwlrd
  database:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5555:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - brtwlrd

  provision:
    build:
      context: ./postgres
    environment:
      DB_HOST: database
      DB_PORT: '5432'
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres
    depends_on:
      database:
        condition: service_healthy
    restart: 'no'
    networks:
      - brtwlrd

  auth:
    build:
      dockerfile: bun.base.dockerfile
      context: .
    volumes:
      - ../:/usr/src/app
    command: bun micro:auth
    environment:
      DB_DRIVER: postgres
      DB_PASS: jdHG6f09YXAP/0r1FWOUY71yacB3jDXubZ7EHsl9ewQ=
      DB_USER: auth_service
      DB_HOST: database
      DB_NAME: auth

    depends_on:
      provision:
        condition: service_completed_successfully
      broker:
        condition: service_started
    networks:
      - brtwlrd

  gateway:
    build:
      dockerfile: bun.base.dockerfile
      context: .
    volumes:
      - ../:/usr/src/app
    command: bun micro:gateway
    depends_on:
      provision:
        condition: service_completed_successfully
      broker:
        condition: service_started
    networks:
      - brtwlrd
    ports:
      - '3000:3000'

volumes:
  postgres_data:

networks:
  brtwlrd:
